FROM debian:buster

RUN apt update && \
    apt install php php-fpm php-cli php-opcache php-gd
# RUN apt install php-mysql php-bcmath \
#     php-ctype php-json php-mbstring php-pdo \
#     php-tokenizer php-xml php-curl &&\


